# Generated by Django 3.2.16 on 2023-04-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Akun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumuser',
            old_name='n_phone',
            new_name='Nomor_phone',
        ),
    ]
