# Generated by Django 3.2.16 on 2023-05-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Akun', '0002_rename_n_phone_costumuser_nomor_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostumUser',
        ),
    ]
